server:
  port: 8089
spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081
#          predicates:
#            - Path=/customers/**
#        - id: r2
#          uri: http://localhost:8082
#          predicates:
#            - Path=/products/**